{'application': False,
 'author': 'Nedas Zilinskas',
 'auto_install': False,
 'category': 'Website',
 'contributors': 'Nedas Zilinskas',
 'currency': 'EUR',
 'data': ['data/x_website_embed.xml',
          'security/ir.model.access.csv',
          'views/assets.xml',
          'views/snippet.xml',
          'views/x_website_embed.xml'],
 'demo': [],
 'depends': ['website'],
 'description': 'Embed HTML snippets to your website',
 'external_dependencies': [],
 'images': ['static/description/main_screenshot.png'],
 'installable': True,
 'license': 'AGPL-3',
 'live_test_url': 'https://www.youtube.com/watch?v=2NUtSJ9SnJw',
 'maintainer': 'Nedas Zilinskas',
 'name': 'Embed HTML Building Block',
 'price': 25.0,
 'qweb': [],
 'summary': 'Embed HTML snippets to your website',
 'support': 'nedas.zilinskas@gmail.com',
 'version': '11.0.1.0',
 'website': 'http://nedaszilinskas.com'}